# Base image
FROM node:20

# Set working directory inside the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the app
COPY . .


# Expose port
EXPOSE 5000

# Start the app
CMD ["node", "server.js"]
